// Immediately Invoked Function Expressions (IIFE)

function chai(){
    //named IIFE
    console.log(`DATABASE CONNECTED`);
}
//chai()                    


//Global scope pollution created/generated by pollution while remove that problem from global declaretion or variable pollution we use IIFE

 (function chai(){
    console.log(`database connected`);
    })();


( (name) => {
    console.log(`database connected two ${name}`);
}) ('haniya')